"""
Convert the CraftPix "Swordsman" sprite sheets into src/gfx/hero-data.js.

The game then rebuilds every frame in code (see buildHero in sprites.js), so
no image files are loaded at runtime.

Usage:
  python tools/extract_hero.py "<path to ...>/PNG/Swordsman_lvl2/Without_shadow"

Each sheet is a grid of 64x64 frames. Rows are directions:
0 = down, 1 = left, 2 = right, 3 = up.
"""
import json
import os
import sys

from PIL import Image

FRAME = 64
DIRS = ["down", "left", "right", "up"]
# name in the game -> (sheet name part, frames per second)
ANIMS = {
    "idle": ("Idle", 8),
    "walk": ("Walk", 10),
    "run": ("Run", 12),
}
# One character per pixel; '.' is transparent. Avoids quotes and backslashes.
ALPHABET = "".join(chr(c) for c in range(33, 127) if chr(c) not in "'\"\\.`$")


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    src = sys.argv[1]
    level = next((p for p in src.replace("\\", "/").split("/") if p.startswith("Swordsman_lvl")), "Swordsman_lvl2")
    out_path = os.path.join(os.path.dirname(__file__), "..", "src", "gfx", "hero-data.js")

    frames = {}  # anim -> dir -> [Image]
    for anim, (part, _) in ANIMS.items():
        sheet = Image.open(os.path.join(src, f"{level}_{part}_without_shadow.png")).convert("RGBA")
        cols = sheet.width // FRAME
        frames[anim] = {
            d: [sheet.crop((c * FRAME, r * FRAME, c * FRAME + FRAME, r * FRAME + FRAME)) for c in range(cols)]
            for r, d in enumerate(DIRS)
        }

    # One crop box shared by every frame, so the feet never jump around.
    boxes = [f.getbbox() for a in frames.values() for fs in a.values() for f in fs if f.getbbox()]
    x0 = min(b[0] for b in boxes)
    y0 = min(b[1] for b in boxes)
    x1 = max(b[2] for b in boxes)
    y1 = max(b[3] for b in boxes)
    w, h = x1 - x0, y1 - y0

    palette = []
    index = {}

    def encode(img):
        chars = []
        for p in img.crop((x0, y0, x1, y1)).getdata():
            if p[3] == 0:
                chars.append(".")
                continue
            hexcol = "#%02x%02x%02x" % p[:3]
            if hexcol not in index:
                index[hexcol] = ALPHABET[len(palette)]
                palette.append(hexcol)
            chars.append(index[hexcol])
        return "".join(chars)

    anims = {
        anim: {"fps": ANIMS[anim][1], "frames": {d: [encode(f) for f in fs] for d, fs in dirs.items()}}
        for anim, dirs in frames.items()
    }
    data = {
        "w": w,
        "h": h,
        # The feet sit on the last row of the crop box.
        "feet": 1,
        "palette": dict(zip((index[c] for c in palette), palette)),
        "anims": anims,
    }

    with open(out_path, "w", encoding="utf8", newline="\n") as f:
        f.write(f"// Generated by tools/extract_hero.py from the CraftPix {level} sheets. Do not edit by hand.\n")
        f.write("// Art (c) CraftPix.net, used under https://craftpix.net/file-licenses/\n")
        f.write("// Each frame is w*h characters, row by row; '.' is transparent, other characters index `palette`.\n")
        f.write("export const HERO = ")
        f.write(json.dumps(data, separators=(",", ":")))
        f.write(";\n")
    n = sum(len(fs) for a in anims.values() for fs in a["frames"].values())
    print(f"{level}: {n} frames, {w}x{h} px, {len(palette)} colours -> {os.path.normpath(out_path)}")


if __name__ == "__main__":
    main()
